### ISSUE TITLE
Support YAML format definition file

### ISSUE THREAD

**Issue by hidakatsuya** [hidakatsuya/rexer#23]
Make as a plugin, like `rexer-yaml`.
```yaml
theme:
  bleuclair:
    github:
      repo: farend/redmine_theme_farend_bleuclair

plugin:
  redmine_ip_filter:
    github: { repo: "redmica/redmine_ip_filter", tag: "v1.0.0" }
  redmine_issue_panel:
    git:
      url: https://github.com/redmica/redmine_issue_panel
    installed: |
      Pathname.new("config/config.yml").write <<~CONF
        ....
      CONF
```
